from typing import Protocol

from app.domain.models import Appointment, Doctor, Patient, User


class UserRepository(Protocol):
    def find_by_email(self, email: str) -> User | None: ...


class PatientRepository(Protocol):
    def list(self, search: str | None = None, status: str | None = None) -> list[Patient]: ...
    def get(self, patient_id: str) -> Patient | None: ...
    def create(self, patient: Patient) -> Patient: ...
    def delete(self, patient_id: str) -> None: ...


class DoctorRepository(Protocol):
    def list(self) -> list[Doctor]: ...


class AppointmentRepository(Protocol):
    def list(self) -> list[Appointment]: ...
    def create(self, appointment: Appointment) -> Appointment: ...
    def cancel(self, appointment_id: str) -> Appointment | None: ...
