from typing import Protocol

from app.domain.models import Appointment, Doctor, Patient, User


class UserRepository(Protocol):
    def find_by_email(self, email: str) -> User | None: ...
    def find_by_id(self, user_id: str) -> User | None: ...


class PatientRepository(Protocol):
    def list(self, search: str | None = None, status: str | None = None) -> list[Patient]: ...
    def get(self, patient_id: str) -> Patient | None: ...
    def create(self, patient: Patient) -> Patient: ...
    def delete(self, patient_id: str) -> None: ...


class DoctorRepository(Protocol):
    def list(self) -> list[Doctor]: ...


class AppointmentRepository(Protocol):
    def list(self) -> list[Appointment]: ...
    def create(self, appointment: Appointment) -> Appointment: ...
    def cancel(self, appointment_id: str) -> Appointment | None: ...


class RefreshSessionRepository(Protocol):
    def create(self, session_id: str, user_id: str, expires_at_ts: int) -> None: ...
    def is_active(self, session_id: str, user_id: str, now_ts: int) -> bool: ...
    def revoke(self, session_id: str) -> None: ...
    def revoke_all_for_user(self, user_id: str) -> None: ...
    def prune_active_sessions(self, user_id: str, max_active: int, now_ts: int) -> None: ...
